Java api
softwaremill/akka-http-session pull request #29
Opened 2017-01-30 13:56 UTC by kijanowski

2017-01-30 19:24 UTC, adamw requested changes
Just some minor changes. Thanks for the tests :)

2017-01-30 19:24 UTC, adamw commented on build.sbt
> +    testOptions in Test := Seq(Tests.Argument(TestFrameworks.JUnit, "-a")),
maybe add a comment that this is needed for javadsl tests?

2017-01-30 19:24 UTC, adamw commented on core/src/main/scala/com/softwaremill/session/CsrfDirectives.scala
> +  def randomTokenCsrfProtection[T](checkMode: CsrfCheckMode[T], inner: Supplier[Route]): Route = RouteAdapter {
is this needed here, can't the code live in `javadsl`? If it's here, users of the scalads will also see the java variants which might be confusing

2017-01-30 19:24 UTC, adamw commented on core/src/main/scala/com/softwaremill/session/RefreshTokenStorage.scala
> +abstract class InMemoryRefreshTokenStorageWrapper[T]() extends InMemoryRefreshTokenStorage[T]
maybe move this to the `javadsl` package? then it can have a name without the -wrapper suffix as well

2017-01-30 19:24 UTC, adamw commented on core/src/main/scala/com/softwaremill/session/SessionConfig.scala
> +  def defaultConfig(serverSecret: String) = fromConfig(ConfigFactory.load()
maybe we can keep the `default` method, and add another one, `defaultConfig`, which would just delegate (or the other way round). We won't break exisitng cod this way

2017-01-30 19:24 UTC, adamw commented on example/src/main/java/com/softwaremill/example/JavaExample.java
> +        sessionTransport = CookieST$.MODULE$;
maybe we can make this nicer with a class in `javadsl` + static aliases?

2017-01-31 08:23 UTC, kijanowski commented on build.sbt
> +    testOptions in Test := Seq(Tests.Argument(TestFrameworks.JUnit, "-a")),
👍

2017-01-31 08:30 UTC, kijanowski commented on core/src/main/scala/com/softwaremill/session/SessionConfig.scala
> +  def defaultConfig(serverSecret: String) = fromConfig(ConfigFactory.load()
yeah, thought about that as well

2017-02-01 11:30 UTC, merged

2017-02-01 12:05 UTC, adamw commented
Release in 0.4.0 - thanks!